name: Build Repository

on:
  push:
    branches:
      - development
    paths:
      - pkgbuilds
  workflow_dispatch:

permissions:
  contents: write
  packages: write

concurrency:
  group: build-repository-${{ github.ref }}
  cancel-in-progress: true

env:
  REPO_NAME: parzival-space
  PKGBUILDS_DIR: pkgbuilds
  RELEASE_TAG: repository

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:multilib-devel
    env:
      REPO_PATH: .repo
      BUILD_USER: builder
    steps:
      - name: Update system & install requirements
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git sudo
      - name: Create build user
        run: |
          useradd -m ${{ env.BUILD_USER }}
          echo "${{ env.BUILD_USER }} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

      - name: Checkout build sources
        uses: actions/checkout@v6
      - name: Update permissions
        run: |
          chown -R builder:builder .

      - name: Build parzival-gaming-meta
        working-directory: ./${{ env.PKGBUILDS_DIR }}/parzival-gaming-meta
        run: |
          sudo -u builder makepkg -sri --noconfirm

      - name: Build eso-addons-manager-bin
        working-directory: ./${{ env.PKGBUILDS_DIR }}/eso-addons-manager-bin
        run: |
          sudo -u builder makepkg -sri --noconfirm

      - name: Add built packages to repository
        run: |
          # patch package names to replace ':' with '_' for github compatibility
          find ./${{ env.PKGBUILDS_DIR }}/ -name "*.pkg.tar.zst" -exec bash -c 'mv "$0" "${0//:/_}"' {} \;
          
          sudo -u builder mkdir -p ./${{ env.REPO_PATH }}
          sudo -u builder repo-add ./${{ env.REPO_PATH }}/${{ env.REPO_NAME }}.db.tar.gz ./${{ env.PKGBUILDS_DIR }}/**/*.pkg.tar.zst
          sudo -u builder cp ./${{ env.PKGBUILDS_DIR }}/**/*.pkg.tar.zst ./${{ env.REPO_PATH }}/

      - name: test - compress repository into archive to bypass stupid ntfs check
        run: |
          sudo -u builder tar -czf ${{ env.REPO_NAME }}-repo.tar.gz ${{ env.REPO_PATH }}

      - name: Upload a Build Artifact
        uses: ncipollo/release-action@v1
        with:
          tag: '${{ env.RELEASE_TAG }}'
          omitBody: 'true'
          omitName: 'true'
          allowUpdates: 'true'
          artifacts: '${{ env.REPO_PATH }}/*.*'

