name: Build Repository

on:
  push:
    branches:
      - development
    paths:
      - pkgbuilds/**
  workflow_dispatch:

permissions:
  contents: write
  packages: write

concurrency:
  group: build-repository-${{ github.ref }}-pkgs
  cancel-in-progress: true

env:
  REPO_NAME: parzival-space
  PKGBUILDS_DIR: pkgbuilds
  RELEASE_TAG: repository

jobs:
  build_packages:
    runs-on: ubuntu-latest
    container:
      image: archlinux:multilib-devel
    strategy:
      matrix:
        include:
          - name: parzival-gaming-meta
          - name: eso-addons-manager-bin
          - name: eso-addons-manager
    env:
      BUILD_USER: builder
    steps:
      - name: Update system & install requirements
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git sudo
      - name: Checkout build sources
        uses: actions/checkout@v6
      - name: Create build user
        run: |
          useradd -m ${{ env.BUILD_USER }}
          echo "${{ env.BUILD_USER }} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R builder:builder .
      - name: Build ${{ matrix.name }}
        working-directory: ./${{ env.PKGBUILDS_DIR }}/${{ matrix.name }}
        run: |
          sudo -u builder makepkg -sri --noconfirm
      - name: Rename package files for GitHub compatibility
        run: |
          find ./${{ env.PKGBUILDS_DIR }}/${{ matrix.name }}/ -name "*.pkg.tar.zst" -exec bash -c 'mv "$0" "${0//:/_}"' {} \;
      - name: Upload ${{ matrix.name }} package artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          name: ${{ matrix.name }}-package
          include-hidden-files: 'true'
          path: ./${{ env.PKGBUILDS_DIR }}/${{ matrix.name }}/*.pkg.tar.zst

  build_repository:
    needs: build_packages
    runs-on: ubuntu-latest
    container:
      image: archlinux:multilib-devel
    env:
      BUILD_USER: builder
    steps:
      - name: Update system & install requirements
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git sudo
      - name: Download built package artifacts
        uses: actions/download-artifact@v5
        with:
          path: './packages'
          pattern: '*-package'
          merge-multiple: 'true'
      - name: Create build user
        run: |
          useradd -m ${{ env.BUILD_USER }}
          echo "${{ env.BUILD_USER }} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R builder:builder .
      - name: Add built packages to repository
        run: |
          ls -la ./packages
          sudo -u builder mkdir -p ./repository
          sudo -u builder repo-add ./repository/${{ env.REPO_NAME }}.db.tar.gz ./packages/*.pkg.tar.zst
          
          # copy all built packages (excluding debug packages) to ./repository
          sudo -u builder cp ./packages/*.pkg.tar.zst ./repository/
          sudo -u builder find ./repository/ -name "*-debug-*.pkg.tar.zst" -delete
      - name: Upload a Build Artifact
        uses: ncipollo/release-action@v1
        with:
          tag: '${{ env.RELEASE_TAG }}'
          omitBody: 'true'
          omitName: 'true'
          allowUpdates: 'true'
          artifacts: './repository/*.*'

