name: Build Repository
on:
  push:
    branches:
      - development
    paths:
      - pkgbuilds/**
  workflow_dispatch:

permissions:
  contents: write
  packages: write

concurrency:
  group: build-repository-${{ github.ref }}
  cancel-in-progress: true

env:
  REPO_NAME: parzival-space
  PKGBUILDS_DIR: pkgbuilds
  RELEASE_TAG: repository

jobs:
  find_packages:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.set-packages.outputs.packages }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Find packages
        id: set-packages
        run: |
          # find directories in pkgbuilds containing a PKGBUILD
          packages=$(
            find ${{ env.PKGBUILDS_DIR }} -mindepth 2 -maxdepth 2 -type f -name PKGBUILD \
            -exec dirname {} \; \
            | sed 's|^pkgbuilds/||' \
            | xargs -n 1 basename \
            | sort -u \
            | awk '{ printf "%s\"%s\"", sep, $0; sep=", " }'
          )
          echo "packages=[$packages]" >> $GITHUB_OUTPUT
          echo "Found packages: $packages"

  build_packages:
    needs: find_packages
    runs-on: ubuntu-latest
    container:
      image: archlinux:multilib-devel
    strategy:
      matrix:
        name: ${{ fromJson(needs.find_packages.outputs.packages) }}
    env:
      BUILD_USER: builder
    steps:
      - name: Update system & install requirements
        run: |
          pacman-key --init
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git sudo
      - name: Checkout build sources
        uses: actions/checkout@v6
      - name: Create build user
        run: |
          useradd -m ${{ env.BUILD_USER }}
          echo "${{ env.BUILD_USER }} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R builder:builder .
      - name: Build ${{ matrix.name }}
        working-directory: ./${{ env.PKGBUILDS_DIR }}/${{ matrix.name }}
        run: |
          sudo -u builder makepkg -sri --noconfirm
      - name: Rename package files for GitHub compatibility
        run: |
          find ./${{ env.PKGBUILDS_DIR }}/${{ matrix.name }}/ -name "*.pkg.tar.zst" -exec bash -c 'mv "$0" "${0//:/_}"' {} \;
      - name: Upload ${{ matrix.name }} package artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: ${{ matrix.name }}-package
          include-hidden-files: 'true'
          path: ./${{ env.PKGBUILDS_DIR }}/${{ matrix.name }}/*.pkg.tar.zst

  build_repository:
    needs: build_packages
    runs-on: ubuntu-latest
    container:
      image: archlinux:multilib-devel
    env:
      BUILD_USER: builder
    steps:
      - name: Update system & install requirements
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git sudo
      - name: Download built package artifacts
        uses: actions/download-artifact@v8
        with:
          path: './packages'
          pattern: '*-package'
          merge-multiple: 'true'
      - name: Create build user
        run: |
          useradd -m ${{ env.BUILD_USER }}
          echo "${{ env.BUILD_USER }} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R builder:builder .
      - name: Add built packages to repository
        run: |
          # delete debug packages from ./packages
          sudo -u builder find ./packages/ -name "*-debug-*.pkg.tar.zst" -delete
          
          ls -la ./packages
          sudo -u builder mkdir -p ./repository
          sudo -u builder repo-add ./repository/${{ env.REPO_NAME }}.db.tar.gz ./packages/*.pkg.tar.zst
          sudo -u builder cp ./packages/*.pkg.tar.zst ./repository/
      - name: Update Repository Release
        uses: ncipollo/release-action@v1
        with:
          tag: '${{ env.RELEASE_TAG }}'
          omitName: 'true'
          allowUpdates: 'true'
          artifacts: './repository/*.*'
          body: |
            ### Repository Installation
            Add the following code snippet to your `/etc/pacman.conf` file:
            
            ```
            [parzival-space]
            SigLevel = Optional TrustAll
            Server = https://github.com/${{ github.repository }}/releases/download/${{ env.RELEASE_TAG }}
            ```
  
            Then, run `sudo pacman -Sy` to update your package database.

