name: Sync AUR packages
on:
#  push:
#    branches:
#      - development
#    paths:
#      - pkgbuilds/**
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: sync-aur-${{ github.ref }}
  cancel-in-progress: false

env:
  PKGBUILDS_DIR: ./pkgbuilds

jobs:
  find_packages:
    name: "Find packages"
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.set-packages.outputs.packages }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Find packages
        id: set-packages
        run: |
          # find directories in pkgbuilds containing a PKGBUILD
          packages=$(
            find ${{ env.PKGBUILDS_DIR }} -mindepth 2 -maxdepth 2 -type f -name PKGBUILD \
            -exec dirname {} \; \
            | sed 's|^pkgbuilds/||' \
            | xargs -n 1 basename \
            | sort -u \
            | awk '{ printf "%s\"%s\"", sep, $0; sep=", " }'
          )
          echo "packages=[$packages]" >> $GITHUB_OUTPUT
          echo "Found packages: $packages"

  verify_build:
    name: "Verify build for ${{ matrix.package }}"
    needs: find_packages
    runs-on: ubuntu-latest
    container:
      image: archlinux:multilib-devel
    strategy:
      matrix:
        package: ${{ fromJson(needs.find_packages.outputs.packages) }}
      fail-fast: false
    env:
      BUILD_USER: builder
    steps:
      - name: Update system & install requirements
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git sudo
      - name: Checkout build sources
        uses: actions/checkout@v6
      - name: Create build user
        run: |
          useradd -m ${{ env.BUILD_USER }}
          echo "${{ env.BUILD_USER }} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R builder:builder .
      - name: Build ${{ matrix.name }}
        working-directory: ./${{ env.PKGBUILDS_DIR }}/${{ matrix.name }}
        run: |
          sudo -u builder makepkg -sri --noconfirm

  sync_with_aur:
    name: "Sync ${{ matrix.package }}"
    needs:
      - find_packages
      - verify_build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJson(needs.find_packages.outputs.packages) }}
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Check if package should be ignored
        working-directory: "./${{ env.PKGBUILDS_DIR }}/${{ matrix.package }}"
        id: aur_check
        run: |
          # ignore packages that contain a .no-aur-sync file
          if [ -f .no-aur-sync ]; then
              echo "Package ${{ matrix.package }} is marked to be ignored for AUR sync."
              echo "ignore=true" >> $GITHUB_OUTPUT
          else
              echo "ignore=false" >> $GITHUB_OUTPUT
          fi
      - name: Generate commit message
        working-directory: "./${{ env.PKGBUILDS_DIR }}/${{ matrix.package }}"
        id: commit_message
        run: |
          # generate commit message based on latest commit affecting the PKGBUILD
          latest_commit=$(git log -n 1 --pretty=format:"%s" -- "./")
          
          # extract version from PKGBUILD
          pkgbuild_pkgver=$(grep -E '^pkgver=' "./PKGBUILD" | cut -d'=' -f2)
          pkgbuild_pkgrel=$(grep -E '^pkgrel=' "./PKGBUILD" | cut -d'=' -f2)
          
          echo "commit_message<<EOF" >> $GITHUB_OUTPUT
          echo "Version bump to ${pkgbuild_pkgver}-${pkgbuild_pkgrel}" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "Latest commit message:" >> $GITHUB_OUTPUT
          echo "${latest_commit}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Collect additional assets
        working-directory: "./${{ env.PKGBUILDS_DIR }}/${{ matrix.package }}"
        id: collect_assets
        run: |
          # load PKGBUILD source PKGBUILD and specify all assets not starting with http:// or https://
          # workaround for https://github.com/KSXGitHub/github-actions-deploy-aur/issues/36
          source "./PKGBUILD"
          echo "assets<<EOF" >> $GITHUB_OUTPUT
          for src in ${source[@]}; do
              # split at :: and check last entry for URL prefix
              src_file=$(echo "$src" | awk -F '::' '{print $NF}')
              if [[ ! "$src_file" =~ ^https?:// ]]; then
                  echo "${{ env.PKGBUILDS_DIR }}/${{ matrix.package }}/$src_file" >> $GITHUB_OUTPUT
              fi
          done
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.2
        if: steps.aur_check.outputs.ignore != 'true'
        with:
          pkgname: ${{ matrix.package }}
          pkgbuild: "./${{ env.PKGBUILDS_DIR }}/${{ matrix.package }}/PKGBUILD"
          commit_message: ${{ steps.commit_message.outputs.commit_message }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          commit_username: ${{ secrets.AUR_USERNAME }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          test: false # already tested in previous job
          allow_empty_commits: false # prevent commits with no changes
          assets: ${{ steps.collect_assets.outputs.assets }}

